import React,{useEffect,useState} from 'react';
import './control-dashboard.css';
type Job={id:string;kind:string;status:string;error?:string;events:{stage:string;detail:string;status:string}[];result?:unknown};
type Version={id:string;status:string;digest:string;spec:{name:string;code:string;requirements:string[]};diff:string;successes:number;failures:number};
type ManagedService={name:string;status:string;healthy:boolean;image:string;resolved_image?:string;memory_bytes?:number;memory_limit_bytes?:number;cpu_percent?:number;restart_count?:number};
type ManagedProject={name:string;file_count:number;bytes:number;updated_at?:number;snapshots:{id:string;created_at:number}[];spec:{repository?:string;runtime_image:string;service?:string}};
type PipelineVersion={id:string;status:string;successes:number;failures:number;spec:{name:string;domain:string;stages:{id:string;kind:string;url:string}[]}};
type ApiCandidate={id:string;endpoint:string;verification_status:string;cost_status:string;license_status:string;evidence:string[]};
type Control={jobs:Job[];versions:Version[];evaluations:{version:string;passed:number;count:number;eligible:boolean;details:{query:string;passed:boolean;reason:string}[]}[];pipeline_versions:PipelineVersion[];pipeline_evaluations:{version:string;eligible:boolean;stage?:string;diagnostics:unknown[]}[];api_candidates:ApiCandidate[];proxies:{id:string;healthy:boolean;latency_ms:number;expires_at:number}[];connectors:{id:string;mode:string;endpoint:string;key_configured:boolean;enabled:boolean}[];managed_services:ManagedService[];managed_projects:ManagedProject[];policies:Record<string,unknown>[];remote_quotas:{provider:string;remaining:number}[];crawls:{id:string;max_pages:number;interval_seconds:number}[];datasets:{id:string;plan:string;count:number}[];audit:{action:string;version:string;at:number}[]};
const API=process.env.REACT_APP_API_URL||'';
async function request<T>(path:string,body?:unknown):Promise<T>{const r=await fetch(API+'/api'+path,body===undefined?undefined:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;}
const labels:Record<string,string>={queued:'В очереди',running:'Выполняется',completed:'Завершено',failed:'Ошибка',blocked:'Ожидает настройки',candidate:'Кандидат',canary:'Пробная версия',active:'Активна',rolled_back:'Откачена',rejected:'Не прошла проверку',tested:'Проверена'};
const connectorExample={id:'my-search',mode:'search',endpoint:'https://api.example.com/search',method:'POST',query_param:'query',sources_field:'results',url_field:'url',title_field:'title',snippet_field:'content',monthly_limit:100,cost:1};
const policyExample={domain:'example.com',timeout:20,wait_selector:'body',min_chars:100,preferred:['httpx'],blocked_markers:['verify you are human','access denied'],official_urls:[],extractors:{title:'h1'}};
const crawlExample={id:'my-monitor',urls:['https://example.com'],max_pages:10,follow_links:false,interval_seconds:0,enabled:true};
const projectExample={name:'my-engine',runtime_image:'inet-sandbox-workspace:local',repository:'https://github.com/owner/repository.git',revision:'main',files:{},service:'',test_commands:[{argv:['python','-m','pytest','-q'],timeout:300,network:false}],memory_mb:1024,cpus:1,pids:256};
export default function ControlPanel(){
 const [data,setData]=useState<Control|null>(null),[tab,setTab]=useState('jobs'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [discovery,setDiscovery]=useState('web scraping language:Python stars:>100');
 const [pipelineUrl,setPipelineUrl]=useState('https://example.com/');
 const [json,setJson]=useState(JSON.stringify(connectorExample,null,2)),[key,setKey]=useState(''),[provider,setProvider]=useState('tavily');
 const [policy,setPolicy]=useState(JSON.stringify(policyExample,null,2)),[crawl,setCrawl]=useState(JSON.stringify(crawlExample,null,2));
 const [project,setProject]=useState(JSON.stringify(projectExample,null,2)),[repairProject,setRepairProject]=useState(''),[repairIssue,setRepairIssue]=useState('');
 const [sources,setSources]=useState('https://raw.githubusercontent.com/proxifly/free-proxy-list/main/proxies/all/data.txt');
 const [sandbox,setSandbox]=useState('Проверка…');
 const [adapter,setAdapter]=useState(JSON.stringify({name:'my-adapter',mode:'fetch',description:'',code:'def run(query, limit):\n    raise NotImplementedError("Implement adapter")',requirements:[]},null,2));
 useEffect(()=>{let live=true;const refresh=async()=>{try{const d=await request<Control>('/control');if(live)setData(d);}catch(e){if(live)setError(String(e));}};refresh();request<{status:string}>('/sandbox/health').then(r=>{if(live)setSandbox(r.status==='ok'?'Готова':r.status);}).catch(()=>{if(live)setSandbox('Недоступна');});const timer=setInterval(refresh,2000);return()=>{live=false;clearInterval(timer);};},[]);
 async function action(path:string,body:unknown){setBusy(true);setError('');setNotice('');try{await request(path,body);setData(await request<Control>('/control'));setNotice('Сохранено. Ход выполнения отражается в журнале.');return true;}catch(e){setError(e instanceof Error?e.message:String(e));return false;}finally{setBusy(false);}}
 async function parsed(path:string,value:string,extra?:Record<string,unknown>){try{await action(path,extra?{spec:JSON.parse(value),...extra}:JSON.parse(value));}catch{setError('Некорректный JSON');}}
 const job=(kind:string,payload:Record<string,unknown>={})=>action('/jobs',{kind,payload});
 const recentJobs=data?.jobs.slice(0,12)||[];
 const latestPipelines=(data?.pipeline_versions||[]).filter((pipeline,index,all)=>all.findIndex(item=>item.spec.domain===pipeline.spec.domain)===index);
 const completedJobs=data?.jobs.filter(item=>item.status==='completed').length||0;
 const failedJobs=data?.jobs.filter(item=>['failed','blocked'].includes(item.status)).length||0;
 return <div className="wide-page control-page"><div className="page-heading"><div className="eyebrow">AUTONOMOUS OPERATIONS</div><h1>Лаборатория инструментов</h1><p>От обнаружения кандидата до проверенной версии в рабочем маршруте.</p></div><div className="control-status">Песочница: <strong>{sandbox}</strong><span>Заданий в очереди: {data?.jobs.filter(j=>j.status==='queued').length||0}</span></div>
 <div className="control-tabs" role="tablist">{[['jobs','Queue'],['versions','Versions'],['pipelines','Repair loop'],['services','Tools'],['projects','Projects'],['proxies','Proxies'],['connectors','Connections'],['policies','Site rules'],['crawls','Crawling']].map(([id,label])=><button role="tab" aria-selected={tab===id} key={id} onClick={()=>{setTab(id);setNotice('');setError('');}}>{label}</button>)}</div>
 {error&&<div className="error-banner" role="alert">{error}</div>}{notice&&<p className="control-notice" role="status">{notice}</p>}
 {tab==='jobs'&&<><div className="automation-overview"><div><small>ВСЕГО</small><strong>{data?.jobs.length||0}</strong><span>заданий</span></div><div><small>УСПЕШНО</small><strong>{completedJobs}</strong><span>проверок</span></div><div><small>ТРЕБУЮТ ВНИМАНИЯ</small><strong>{failedJobs}</strong><span>с диагностикой</span></div><div><small>В ОЧЕРЕДИ</small><strong>{data?.jobs.filter(j=>['queued','running'].includes(j.status)).length||0}</strong><span>сейчас</span></div></div><section className="system-card discovery-card"><div><h2>Найти и подключить инструмент</h2><p className="muted">Discovery проверяет репозитории, затем отправляет кандидата в изолированную разработку.</p></div><form onSubmit={e=>{e.preventDefault();job('discover',{query:discovery,integrate:true});}} className="control-inline"><input aria-label="Запрос обнаружения инструментов" value={discovery} onChange={e=>setDiscovery(e.target.value)}/><button disabled={busy||!discovery.trim()}>Запустить</button></form></section><div className="section-heading"><div><h2>Последние задания</h2><p>Выполняющиеся операции раскрываются автоматически и обновляются каждые 2 секунды.</p></div><div className="control-actions"><button disabled={busy} onClick={()=>job('metadata')}>Обновить метаданные</button><button disabled={busy} onClick={()=>job('quotas')}>Проверить квоты</button></div></div><div className="jobs-grid">{recentJobs.length?recentJobs.map(j=><details className="job-card" key={j.id} open={j.status==='running'?true:undefined}><summary><span className={'job-kind-icon '+j.status}>{j.status==='completed'?'✓':j.status==='running'?'◌':j.status==='failed'?'!':'◇'}</span><div><b>{j.kind}{j.status==='running'?' · LIVE':''}</b><small>{j.events.at(-1)?.detail||j.id.slice(0,8)}</small></div><span className={'tag '+j.status}>{labels[j.status]||j.status}</span></summary>{j.error&&<p className="job-error">{j.error}</p>}{j.events.map((e,i)=><p className="job-event" key={i}><b>{e.stage}</b> {e.detail}</p>)}{j.result!==undefined&&<pre>{JSON.stringify(j.result,null,2)}</pre>}</details>):<p className="empty-inline">Пока нет заданий.</p>}</div></>}
 {tab==='versions'&&<><details className="system-card"><summary>Добавить адаптер или новую ревизию вручную</summary><p className="muted">Контракт: run(query, limit) возвращает content/status/final_url/sources для fetch либо sources для search. Зависимости фиксируются как package==version. Для ревизии укажите parent.</p><textarea className="json-editor" aria-label="Спецификация адаптера" value={adapter} onChange={e=>setAdapter(e.target.value)}/><button className="control-primary" disabled={busy} onClick={()=>parsed('/versions',adapter)}>Создать кандидата</button></details>{data?.versions.map(v=><section className="system-card version-card" key={v.id}><div className="version-heading"><h2>{v.spec.name}</h2><span className="tag">{labels[v.status]||v.status}</span></div><small>{v.id} · {v.successes} успехов / {v.failures} ошибок</small><div className="control-actions"><button disabled={busy} onClick={()=>job('evaluate',{version:v.id,promote:true})}>Запустить испытания</button><button disabled={busy||!data.evaluations.some(e=>e.version===v.id&&e.eligible)} onClick={()=>action(`/versions/${v.id}/promote`,{})}>Продвинуть</button><button disabled={busy||!['active','canary'].includes(v.status)} onClick={()=>action(`/versions/${v.id}/rollback`,{})}>Откатить</button></div><details><summary>Код и изменения</summary><pre>{v.spec.code}</pre><pre>{v.diff}</pre><p>{v.spec.requirements.join(', ')||'Без дополнительных зависимостей'}</p></details>{data.evaluations.filter(e=>e.version===v.id).map(e=><details key={e.version}><summary>Результаты: {e.passed}/{e.count}</summary>{e.details.map((d,i)=><p key={i}>{d.passed?'✓':'×'} {d.query} {d.reason}</p>)}</details>)}</section>)}{!data?.versions.length&&<p className="empty-inline">Адаптеры появятся после разработки кандидатов или ручного добавления.</p>}</>}
 {tab==='services'&&<><section className="system-card"><h2>Управляемые инструменты</h2><p className="muted">Агент разворачивает сервисные инструменты в изолированной Docker-сети, ограничивает CPU, RAM и PID, проверяет готовность и автоматически перезапускает сбойные экземпляры.</p><div className="control-actions"><button disabled={busy} onClick={()=>job('provision',{profile:'searxng'})}>Поднять SearXNG</button><button disabled={busy} onClick={()=>job('services')}>Обновить состояние</button></div></section>{data?.managed_services.map(s=><section className="case-card" key={s.name}><h3>{s.name}</h3><p>{s.image}</p><span className="tag">{s.status} · {s.healthy?'healthy':'unhealthy'}</span><p className="muted">RAM {Math.round((s.memory_bytes||0)/1048576)} / {Math.round((s.memory_limit_bytes||0)/1048576)} МБ · CPU {s.cpu_percent||0}% · перезапусков {s.restart_count||0}</p><div className="control-actions"><button disabled={busy} onClick={()=>action(`/services/${s.name}/restart`,{})}>Перезапустить</button><button disabled={busy||s.status!=='running'} onClick={()=>action(`/services/${s.name}/stop`,{})}>Остановить</button></div></section>)}{!data?.managed_services.length&&<p className="empty-inline">Постоянные инструменты ещё не развёрнуты.</p>}</>}
 {tab==='projects'&&<><section className="system-card"><h2>Редактируемые проекты и движки</h2><p className="muted">Исходники хранятся в изолированном volume. Перед каждым изменением создаётся snapshot; тесты идут с лимитами CPU/RAM и без сети по умолчанию. Неуспешная правка автоматически откатывается.</p><textarea className="json-editor" aria-label="Спецификация управляемого проекта" value={project} onChange={e=>setProject(e.target.value)}/><button className="control-primary" disabled={busy} onClick={()=>parsed('/projects',project)}>Создать или подключить проект</button></section><section className="system-card"><h2>Автономное исправление</h2><div className="control-inline"><select aria-label="Проект" value={repairProject} onChange={e=>setRepairProject(e.target.value)}><option value="">Выберите проект</option>{data?.managed_projects.map(p=><option key={p.name} value={p.name}>{p.name}</option>)}</select><input aria-label="Описание проблемы" value={repairIssue} onChange={e=>setRepairIssue(e.target.value)} placeholder="Что сломано и какой результат ожидается"/><button disabled={busy||!repairProject||!repairIssue.trim()} onClick={()=>job('workspace_repair',{project:repairProject,issue:repairIssue})}>Исправить и проверить</button></div></section>{data?.managed_projects.map(p=><section className="case-card" key={p.name}><h3>{p.name}</h3><p>{p.spec.repository||'Локально созданный проект'}</p><span className="tag">{p.file_count} файлов · {Math.round(p.bytes/1024)} КБ</span><p className="muted">Runtime: {p.spec.runtime_image}{p.spec.service?` · сервис: ${p.spec.service}`:''} · snapshots: {p.snapshots?.length||0}</p></section>)}{!data?.managed_projects.length&&<p className="empty-inline">Редактируемые проекты ещё не подключены.</p>}</>}
 {tab==='proxies'&&<><section className="system-card"><h2>Источники прокси</h2><p className="muted">Проверяются публичный IP, HTTPS CONNECT с проверкой TLS и контрольное содержимое. Срок действия результата — 15 минут.</p><textarea className="json-editor short-editor" aria-label="Источники прокси" value={sources} onChange={e=>setSources(e.target.value)}/><div className="control-actions"><button disabled={busy} onClick={()=>action('/proxies/sources',{sources:sources.split('\n').map(x=>x.trim()).filter(Boolean)})}>Сохранить источники</button><button disabled={busy} onClick={()=>job('proxies')}>Обновить и проверить</button></div></section><div className="control-table"><table><thead><tr><th>Адрес</th><th>Состояние</th><th>Задержка</th></tr></thead><tbody>{data?.proxies.map(p=><tr key={p.id}><td>{p.id}</td><td>{p.expires_at*1000<Date.now()?'Истёк TTL':p.healthy?'Доступен':'Недоступен'}</td><td>{p.latency_ms} ms</td></tr>)}</tbody></table></div></>}
 {tab==='connectors'&&<><section className="system-card"><h2>Ключ встроенного сервиса</h2><form className="control-inline" onSubmit={async e=>{e.preventDefault();if(await action('/keys',{provider,key}))setKey('');}}><select aria-label="Сервис для ключа" value={provider} onChange={e=>setProvider(e.target.value)}><option value="tavily">Tavily</option><option value="firecrawl">Firecrawl</option><option value="capsolver">CapSolver</option><option value="twocaptcha">2Captcha</option></select><input type="password" autoComplete="off" aria-label="API-ключ" placeholder="API-ключ" value={key} onChange={e=>setKey(e.target.value)}/><button disabled={busy||!key}>Сохранить ключ</button></form><p className="muted">Ключ шифруется перед записью и не возвращается через API.</p></section><section className="system-card"><h2>Подключить произвольный Search / Fetch API</h2><textarea className="json-editor" aria-label="Конфигурация API" value={json} onChange={e=>setJson(e.target.value)}/><p className="muted">Поле выше задаёт URL, контракт, бюджет и при необходимости usage_endpoint / remaining_path. Ключ берётся из поля API-ключа.</p><button className="control-primary" disabled={busy} onClick={async()=>{try{if(await action('/connectors',{spec:JSON.parse(json),key:key||undefined}))setKey('');}catch{setError('Некорректный JSON');}}}>Сохранить подключение</button></section>{data?.connectors.map(c=><section className="case-card" key={c.id}><h3>{c.id} · {c.mode}</h3><p>{c.endpoint}</p><span className="tag">{c.enabled?'Включён':'Выключен'} · {c.key_configured?'Ключ настроен':'Без ключа'}</span></section>)}{data?.remote_quotas.map(q=><p key={q.provider}>{q.provider}: осталось {q.remaining} кредитов</p>)}</>}
 {tab==='policies'&&<><section className="system-card"><h2>Правила для домена</h2><p className="muted">Таймаут, ожидание селектора, порог качества, официальные источники и CSS-поля для парсинга. Каждое изменение сохраняется как ревизия.</p><textarea className="json-editor" aria-label="Правила домена" value={policy} onChange={e=>setPolicy(e.target.value)}/><button className="control-primary" disabled={busy} onClick={()=>parsed('/policies',policy)}>Сохранить правила</button></section>{data?.policies.map((p,i)=><details className="case-card" key={i}><summary>{String(p.domain)}</summary><pre>{JSON.stringify(p,null,2)}</pre><button onClick={()=>setPolicy(JSON.stringify(p,null,2))}>Редактировать</button></details>)}</>}
 {tab==='crawls'&&<><section className="system-card"><h2>План парсинга</h2><p className="muted">До 50 страниц, переходы внутри исходных доменов, повтор по расписанию. Для извлечения полей задайте extractors в правилах сайта.</p><textarea className="json-editor" aria-label="План парсинга" value={crawl} onChange={e=>setCrawl(e.target.value)}/><button className="control-primary" disabled={busy} onClick={()=>parsed('/crawls',crawl)}>Сохранить план</button></section>{data?.crawls.map(c=><section className="case-card" key={c.id}><h3>{c.id}</h3><p>До {c.max_pages} страниц · {c.interval_seconds?`каждые ${c.interval_seconds} с`:'ручной запуск'}</p><button disabled={busy} onClick={()=>job('crawl',{plan:c.id})}>Запустить</button></section>)}<h2 className="section-title">Собранные данные</h2>{data?.datasets.map(d=><div className="dataset-row" key={d.id}><b>{d.plan}</b><span>{d.count} страниц</span><a href={`${API}/api/datasets/${d.id}`} target="_blank" rel="noreferrer">JSON ↗</a><a href={`${API}/api/datasets/${d.id}?format=csv`}>Скачать CSV</a></div>)}</>}
 {tab==='pipelines'&&<><div className="automation-overview"><div><small>ДОМЕНЫ</small><strong>{latestPipelines.length}</strong><span>адаптированы</span></div><div><small>РАБОТАЮТ</small><strong>{latestPipelines.filter(p=>['active','canary','tested'].includes(p.status)).length}</strong><span>pipeline</span></div><div><small>API</small><strong>{data?.api_candidates.filter(a=>a.verification_status==='verified_unauthenticated').length||0}</strong><span>проверено</span></div><div><small>FALLBACK</small><strong>4</strong><span>уровня</span></div></div><section className="system-card pipeline-designer"><div><div className="eyebrow">AUTONOMOUS REPAIR</div><h2>Спроектировать маршрут для сайта</h2><p className="muted">API/feeds → JSON-LD → semantic HTML → browser. Новая версия включается только после live-проверки.</p></div><form className="control-inline" onSubmit={e=>{e.preventDefault();job('pipeline_design',{url:pipelineUrl});}}><input aria-label="URL источника" value={pipelineUrl} onChange={e=>setPipelineUrl(e.target.value)}/><button disabled={busy||!pipelineUrl}>Проверить сайт</button><button type="button" disabled={busy||!pipelineUrl} onClick={()=>job('discover_apis',{url:pipelineUrl})}>Найти API</button></form></section><div className="section-heading"><div><h2>Активные маршруты</h2><p>Последняя ревизия для каждого домена.</p></div><span className="success-note">● live проверка обязательна</span></div><div className="pipeline-grid">{latestPipelines.map(p=><section className="pipeline-card" key={p.id}><div><span className="pipeline-domain">{p.spec.domain.split('.').slice(-2).join('.')}</span><span className={'tag '+p.status}>{labels[p.status]||p.status}</span></div><h3>{p.spec.domain}</h3><div className="stage-flow">{p.spec.stages.map((stage,index)=><React.Fragment key={stage.id}><span className={stage.kind==='browser'?'browser-stage':''}>{stage.kind.replace('_',' ')}</span>{index<p.spec.stages.length-1&&<i>→</i>}</React.Fragment>)}</div><small>{p.successes} успешных вызовов · {p.failures} ошибок</small></section>)}</div><div className="section-heading"><div><h2>Проверенные API и feeds</h2><p>Endpoints, реально ответившие без ключа.</p></div></div><div className="api-grid">{data?.api_candidates.slice(0,6).map(a=><section className="api-card" key={a.id}><span className="tag">{a.verification_status}</span><h3>{a.endpoint}</h3><p>{a.cost_status}</p></section>)}</div></>}
 </div>;
}
